# 应用程序配置
application:
 name: UPUPOR # 程序名
 version: 1.0.0 # 版本号

server:
 port: 2020 #端口
 servlet:
  context-path: /
  session:
   timeout: PT24H
 netty:
  connection-timeout: 300000

# spring配置
spring:
 #flyway
 flyway:
  enabled: true
  encoding: utf-8
  #sql文件存放位置
  locations: classpath:db/migration
  #版本记录表格
  table: _upupor_db_version_
  baseline-on-migrate: true
  validate-on-migrate: true
 # thymeleaf配置
 thymeleaf:
  # 开启会提高并发能力
  cache: ${THYMELEAF_CACHE:true} # 开发时关闭缓存,不然没法看到实时页面
  prefix: classpath:/templates/
  suffix: .html
  check-template-location: true
  encoding: UTF-8
  mode: HTML # 用非严格的 HTML
  servlet:
   content-type: text/html # spring.thymeleaf.content-type=text/html
 # 静态资源启用版本控制
 resources:
  chain:
   strategy:
    content:
     enabled: true
     paths: /**
 # 数据源配置
 datasource:
  url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&useSSL=false&characterEncoding=utf8
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
  # 连接池配置
  druid:
   initial-size: 5
   max-wait: 60000
   max-active: 10
   time-between-eviction-runs-millis: 60000
   min-evictable-idle-time-millis: 300000
   validation-query: SELECT 1
   test-while-idle: true
   test-on-borrow: false
   test-on-return: false
 # redis配置 redis版本 4.0.9 redis重启后spring服务会自动链接
 redis:
  # 需要开启redis远程访问功能 redis.conf 文件  注释掉bind 127.0.0.1 再改变protected-mode值为no
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  # 配置redis.conf文件requirepass 的值
  # 设置了密码后,使用redis-cli时需要 auth验证 直接输入 auth sDF234sdf#@@$@$fdd即可
  password: ${REDIS_PASSWORD}
  database: 0
 session:
  store-type: redis
 servlet:
  multipart:
   # 开启多文件上传功能
   enabled: true
   # 文件写入磁盘的阈值
   file-size-threshold: 50MB
   # 文件最大
   max-file-size: 20MB
   # 最大请求大小
   max-request-size: 25MB
 mvc:
  async:
   request-timeout: 300000
mybatis-plus:
 mapper-locations: classpath:mybatis/mapper/*.xml

# codingvcr配置
codingvcr:
 # 自定义线程池
 pool:
  corePoolSize: 10
  maxPoolSize: 30
  keepAliveSeconds: 120
 # 广告
 ads: all-top,all-bottom,tech-right-class,tech-right-promote,tech-right-ad,qa,share,workplace
 # 压缩后的图片输出地址
 thumbnails:
  # 压缩质量
  output-quality: ${ALLOW_UPLOAD_PIC_QUALITY}
  # 允许哪些后缀的文件上传
  allows: ${ALLOW_UPLOAD_PIC_SUFFIX}
 #邮件配置
 email:
  # 是否开启邮件推送 0-关闭 -1开启
  on-off: ${EMAIL_ON}
  # 发件人昵称
  sender-nick-name: ${EMAIL_SENDER_NICK_NAME}
  # 控制台创建的发信地址
  sender-account-name: ${EMAIL_SENDER_ACCOUNT}
  accesskey-id: ${EMAIL_ACCESS_KEY}
  accesskey-secret: ${EMAIL_ACCESS_SECRET}
 website: ${WEBSITE}
 # 是否开启广告等推广 0-开启 1-关闭
 ad-switch: ${AD_SWITCH}
 # 右侧广告是否开启
 ad-switch.right: ${AD_SWITCH_RIGHT}
 # 分析开关
 analyze-switch: ${ANALYZE_SWITCH}
 # 文件存储服务
 oss:
  # oss 名称
  bucket-name: ${OSS_BUCKET_NAME}
  # oss 文件存储地址
  file-host: ${OSS_FILE_HOST}
 ossStatic: ${OSS_STATIC}
 env: ${UPUPOR_ENV}
 # 不需要登录的接口
 interfaceWhiteUrlList:
  - /member/get
  - /member/resetPassword
  - /member/add
  - /member/sendVerifyCode
  - /feedback/add
 # 需要登录的页面
 pageCheckUrlList:
  - /editor
  - /radio-station/record
  - /radio-station/create
  - /todo-list
  - /user/manage
  - /m
  - /before-editor
  - /user/admin
 googleAd:
  dataAdClientId: ${GOOGLE_DATA_AD_CLIENT_ID}
  rightSlot: ${GOOGLE_AD_RIGHT}
  feedSlot: ${GOOGLE_AD_FEED}

